### ISSUE TITLE
clicking in mincraft shitted, Im not sure what thoug

### ISSUE THREAD

**Issue by yeetus-maximus** [senseiwells/EssentialClient#103]
I am gonna leave the log in here for you to figure out what I fucked up

`---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/24/23, 4:38 AM
Description: mouseDragged event handler

java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "carpetRule.extraInfo" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at me.senseiwells.essentialclient.feature.CarpetClient.parseRuleToClientRule(CarpetClient.java:320)
	at me.senseiwells.essentialclient.feature.CarpetClient.parseRuleToClientRule(CarpetClient.java:281)
	at me.senseiwells.essentialclient.feature.CarpetClient.lambda$loadSinglePlayerRules$3(CarpetClient.java:166)
	at me.senseiwells.essentialclient.feature.CarpetClient.loadSinglePlayerRules(CarpetClient.java:182)
	at me.senseiwells.essentialclient.feature.CarpetClient.getRule(CarpetClient.java:92)
	at me.senseiwells.essentialclient.utils.EssentialUtils.isCarpetRuleTrue(EssentialUtils.java:205)
	at me.senseiwells.essentialclient.utils.EssentialUtils.isRuleWithCarpet(EssentialUtils.java:201)
	at me.senseiwells.essentialclient.utils.EssentialUtils.isStackableShulkers(EssentialUtils.java:190)
	at net.minecraft.item.ItemStack.handler$cmf000$getMaxCount(ItemStack:1191)
	at net.minecraft.item.ItemStack.getMaxCount(ItemStack)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.calculateOffset(HandledScreen:291)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseDragged(HandledScreen:439)
	at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.mouseDragged(CreativeInventoryScreen:684)
	at net.minecraft.client.Mouse.method_1602(Mouse:197)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490)
	at net.minecraft.client.Mouse.onCursorPos(Mouse:197)
	at net.minecraft.client.Mouse.method_22689(Mouse:164)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22688(Mouse:164)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:165)
	at net.minecraft.client.util.Window.swapBuffers(Window:310)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$efk000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:17108)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:750)
	at net.minecraft.client.main.Main.main(Main:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.senseiwells.essentialclient.feature.CarpetClient.parseRuleToClientRule(CarpetClient.java:320)
	at me.senseiwells.essentialclient.feature.CarpetClient.parseRuleToClientRule(CarpetClient.java:281)
	at me.senseiwells.essentialclient.feature.CarpetClient.lambda$loadSinglePlayerRules$3(CarpetClient.java:166)
	at me.senseiwells.essentialclient.feature.CarpetClient.loadSinglePlayerRules(CarpetClient.java:182)
	at me.senseiwells.essentialclient.feature.CarpetClient.getRule(CarpetClient.java:92)
	at me.senseiwells.essentialclient.utils.EssentialUtils.isCarpetRuleTrue(EssentialUtils.java:205)
	at me.senseiwells.essentialclient.utils.EssentialUtils.isRuleWithCarpet(EssentialUtils.java:201)
	at me.senseiwells.essentialclient.utils.EssentialUtils.isStackableShulkers(EssentialUtils.java:190)
	at net.minecraft.class_1799.handler$cmf000$getMaxCount(class_1799.java:1191)
	at net.minecraft.class_1799.method_7914(class_1799.java)
	at net.minecraft.class_465.method_2379(class_465.java:291)
	at net.minecraft.class_465.method_25403(class_465.java:439)
	at net.minecraft.class_481.method_25403(class_481.java:684)
	at net.minecraft.class_312.method_1602(class_312.java:197)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_481
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at java.lang.Thread.getStackTrace(Unknown Source)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:1021)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.world.World.addDetailsToCrashReport(World:845)
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld:370)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2399)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$efk000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:17108)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:750)
	at net.minecraft.client.main.Main.main(Main:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['i_use_arch'/3, l='ClientLevel', x=-10.99, y=69.24, z=25.37]]
	Chunk stats: 1024, 400
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,56,8), Section: (at 8,8,8 in 0,3,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9567 game time, 9567 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$efk000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:17108)
	at net.minecraft.class_310.method_1514(class_310.java:750)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Faithful-1.17, Faithful-Addons(1), FaithfulRedstone_v5.2.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 6.1.12-1-lts
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 852691712 bytes (813 MiB) / 1415577600 bytes (1350 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 11930.82
	Virtual memory used (MB): 11993.02
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 969.50
	JVM Flags: 3 total; -Xmx4096m -Xms4096m -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		bobby: Bobby 2.1.0
		caffeineconfig: CaffeineConfig 1.0.0+1.17
		carpet: Carpet Mod 1.4.57
		carpet-autocraftingtable: Carpet-AutoCraftingTable 1.4.35
		carpet-extra: Carpet Extra 1.4.57
		carpet-fixes: Carpet Fixes 1.17.1-1.1.0+v210919
		carpet-tis-addition: Carpet TIS Addition 1.45.0
		carpetgamerules: Carpet Gamerules 1.0.0
		chunkdebug: Chunk Debug 1.0.6
		clientcommands: Client Commands 2.5.5
		clientcommands-scripting: Clientcommands Scripting 1.2
		cloth-api: Cloth API 2.1.62
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.1.62
		cloth-common-events-v1: Cloth Common Events v1 2.1.62
		cloth-datagen-api-v1: Cloth Datagen v1 2.1.62
		cloth-scissors-api-v1: Cloth Scissors API v1 2.1.62
		cloth-utils-v1: Cloth Utils v1 2.1.62
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_github_senseiwells_arucas: Arucas d443072775
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		conditional-mixin: conditional mixin 0.3.2
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		dashloader: DashLoader 3.1.1+1.17
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		dropfullcarts: DropFullCarts 1.2.0
		enhancedblockentities: Enhanced Block Entities 0.5+1.17
		essential-client: Essential Client 1.3.2
		fabric: Fabric API 0.46.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+e821752d18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.15+b556f28c18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.6+2a2bb57318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+cf39a74318
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.0+ea29b33318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.6+ce16ae5918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.10+ce16ae5918
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+591a0f2118
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.2.0+48a9ad8918
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.3+3b96517518
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+cf39a74318
		fabricloader: Fabric Loader 0.14.14
		ferritecore: FerriteCore 3.1.0
		g4mespeed: G4mespeed 1.3.4
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		itemscroller: Item Scroller 0.15.0-dev.20211201.010054
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.4
		lazydfu: LazyDFU 0.1.2
		litematica: Litematica 0.9.0
		lithium: Lithium 0.7.5
		magiclib: MagicLib 0.6.212+a47eb26-stable
		magiclib-1_17_1: MagicLib for 1.17.1 0.6.212+a47eb26-stable
		malilib: MaLiLib 0.10.0-dev.26
		masa_gadget_mod: Masa Gadget 3.0.0
		masa_gadget_mod-1_17_1: Masa Gadget for 1.17.1 3.0.0
		memoryleakfix: memory Leak Fix 1.17.1-0.1.1
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.20.0
		minitweaks: MiniTweaks 1.1.5
		modmenu: Mod Menu 2.0.17
		multiconnect-api: MultiConnect API 1.4
		notenoughcrashes: Not Enough Crashes 4.1.4+1.17.1
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.17.1-build.65
		sodium: Sodium 0.3.4+build.13
		sodium-extra: Sodium Extra 0.4.17+mc1.17.1-build.93
		starlight: Starlight 1.0.0+fabric.73f6d37
		tweakeroo: Tweakeroo 0.11.0
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Mesa Intel(R) Xe Graphics (TGL GT2) GL version 4.6 (Core Profile) Mesa 22.3.5, Intel
	Window size: 1900x1025
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glPolygonMode(face)' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/Faithful-1.17 (incompatible), file/Faithful-Addons(1) (incompatible), file/FaithfulRedstone_v5.2.zip
	Current Language: English (US)
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Player Count: 1 / 8; [class_3222['i_use_arch'/3, l='ServerLevel[Computational Redstone]', x=-10.99, y=69.24, z=25.37]]
	Data Packs: vanilla, Fabric Mods
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Essential Client (essential-client)`

**Comment by senseiwells** [comment]
Please update to the latest version of [EssentialClient](https://modrinth.com/mod/essentialclient/versions).

**Comment by yeetus-maximus** [comment]
so this was an oopsie on my part, when will you stop update 1.17?
