### ISSUE TITLE
Can't create java classes: NoClassDefFoundError - net.bytebuddy.ByteBuddy

### ISSUE THREAD

**Issue by Leialoha** [senseiwells/EssentialClient#127]
### Script:
```kt
// temp
experimental(true);
import Java from util.Internal;

RunnableImpl = Java.implementClass([Java.classOf("java.lang.Runnable")], fun(name, args) {
    // ...
});
runnable = RunnableImpl();
runnable.run(); // Will invoke the invokeHandler with the method name and any arguments

```
### StackTrace:
```
FatalError: An unexpected error was thrown
> File: temp, Line: 4, Column: 21, In: Java.implementClass::2
4 | RunnableImpl = Java.implementClass([ ...
  |                     ^
  |                     net/bytebuddy/ByteBuddy
StackTrace (most recent call last)
Caused by: NoClassDefFoundError - net/bytebuddy/ByteBuddy
```
### Crash:
```
me.senseiwells.arucas.exceptions.FatalError: An unexpected error was thrown
Caused by: java.lang.NoClassDefFoundError: net/bytebuddy/ByteBuddy
	at me.senseiwells.arucas.extensions.JavaDef.implementClass(JavaDef.kt:838)
	at me.senseiwells.arucas.extensions.JavaDef.access$implementClass(JavaDef.kt:29)
	at me.senseiwells.arucas.extensions.JavaDef$defineStaticMethods$35.invoke(JavaDef.kt:212)
	at me.senseiwells.arucas.extensions.JavaDef$defineStaticMethods$35.invoke(JavaDef.kt:212)
	at me.senseiwells.arucas.functions.builtin.BuiltInFunction.invoke(BuiltInFunction.kt:77)
	at me.senseiwells.arucas.builtin.FunctionDef.call$Arucas(FunctionDef.kt:26)
	at me.senseiwells.arucas.classes.instance.ClassInstance.call$Arucas(ClassInstance.kt:34)
	at me.senseiwells.arucas.interpreter.Interpreter.call(Interpreter.kt:585)
	at me.senseiwells.arucas.classes.ClassDefinition.staticFunctionCall$Arucas(ClassDefinition.kt:713)
	at me.senseiwells.arucas.interpreter.Interpreter.visitMemberCall(Interpreter.kt:1243)
	at me.senseiwells.arucas.interpreter.Interpreter.visitMemberCall(Interpreter.kt:69)
	at me.senseiwells.arucas.nodes.expressions.MemberCallExpression.visit(MemberCallExpression.kt:20)
	at me.senseiwells.arucas.interpreter.Interpreter.evaluate(Interpreter.kt:667)
	at me.senseiwells.arucas.interpreter.Interpreter.visitAssign(Interpreter.kt:1169)
	at me.senseiwells.arucas.interpreter.Interpreter.visitAssign(Interpreter.kt:69)
	at me.senseiwells.arucas.nodes.expressions.AssignExpression.visit(AssignExpression.kt:19)
	at me.senseiwells.arucas.interpreter.Interpreter.evaluate(Interpreter.kt:667)
	at me.senseiwells.arucas.interpreter.Interpreter.visitExpression(Interpreter.kt:842)
	at me.senseiwells.arucas.interpreter.Interpreter.visitExpression(Interpreter.kt:69)
	at me.senseiwells.arucas.nodes.statements.ExpressionStatement.visit(ExpressionStatement.kt:14)
	at me.senseiwells.arucas.interpreter.Interpreter.execute(Interpreter.kt:659)
	at me.senseiwells.arucas.interpreter.Interpreter.interpret$Arucas(Interpreter.kt:244)
	at me.senseiwells.arucas.interpreter.ThreadHandler.execute$Arucas(ThreadHandler.kt:28)
	at me.senseiwells.arucas.interpreter.Interpreter$Mother.execute(Interpreter.kt:1310)
	at me.senseiwells.arucas.interpreter.Interpreter$executeAsync$1.invoke(Interpreter.kt:202)
	at me.senseiwells.arucas.interpreter.Interpreter$executeAsync$1.invoke(Interpreter.kt:202)
	at me.senseiwells.arucas.interpreter.ThreadHandler.async$lambda-0(ThreadHandler.kt:44)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.ByteBuddy
	... 31 more

```

**Comment by Leialoha** [comment]
### Minecraft Version: `1.20.2`
### Essential Client Version: `1.4.1`
### Arucas Version: `2.3.0`
### Script:
```kt
// temp
experimental(true);
import Java from util.Internal;

RunnableImpl = Java.implementClass([Java.classOf("java.lang.Runnable")], fun(name, args) {

});
runnable = RunnableImpl();
runnable.run(); // Will invoke the invokeHandler with the method name and any arguments

```
### StackTrace:
```
FatalError: An unexpected error was thrown
> File: temp, Line: 4, Column: 21, In: Java.implementClass::2
4 | RunnableImpl = Java.implementClass([ ...
  |                     ^
  |                     net/bytebuddy/ByteBuddy
StackTrace (most recent call last)
Caused by: NoClassDefFoundError - net/bytebuddy/ByteBuddy
```
### Crash:
```
me.senseiwells.arucas.exceptions.FatalError: An unexpected error was thrown
Caused by: java.lang.NoClassDefFoundError: net/bytebuddy/ByteBuddy
	at me.senseiwells.arucas.extensions.JavaDef.implementClass(JavaDef.kt:838)
	at me.senseiwells.arucas.extensions.JavaDef.access$implementClass(JavaDef.kt:29)
	at me.senseiwells.arucas.extensions.JavaDef$defineStaticMethods$35.invoke(JavaDef.kt:212)
	at me.senseiwells.arucas.extensions.JavaDef$defineStaticMethods$35.invoke(JavaDef.kt:212)
	at me.senseiwells.arucas.functions.builtin.BuiltInFunction.invoke(BuiltInFunction.kt:77)
	at me.senseiwells.arucas.builtin.FunctionDef.call$Arucas(FunctionDef.kt:26)
	at me.senseiwells.arucas.classes.instance.ClassInstance.call$Arucas(ClassInstance.kt:34)
	at me.senseiwells.arucas.interpreter.Interpreter.call(Interpreter.kt:585)
	at me.senseiwells.arucas.classes.ClassDefinition.staticFunctionCall$Arucas(ClassDefinition.kt:713)
	at me.senseiwells.arucas.interpreter.Interpreter.visitMemberCall(Interpreter.kt:1243)
	at me.senseiwells.arucas.interpreter.Interpreter.visitMemberCall(Interpreter.kt:69)
	at me.senseiwells.arucas.nodes.expressions.MemberCallExpression.visit(MemberCallExpression.kt:20)
	at me.senseiwells.arucas.interpreter.Interpreter.evaluate(Interpreter.kt:667)
	at me.senseiwells.arucas.interpreter.Interpreter.visitAssign(Interpreter.kt:1169)
	at me.senseiwells.arucas.interpreter.Interpreter.visitAssign(Interpreter.kt:69)
	at me.senseiwells.arucas.nodes.expressions.AssignExpression.visit(AssignExpression.kt:19)
	at me.senseiwells.arucas.interpreter.Interpreter.evaluate(Interpreter.kt:667)
	at me.senseiwells.arucas.interpreter.Interpreter.visitExpression(Interpreter.kt:842)
	at me.senseiwells.arucas.interpreter.Interpreter.visitExpression(Interpreter.kt:69)
	at me.senseiwells.arucas.nodes.statements.ExpressionStatement.visit(ExpressionStatement.kt:14)
	at me.senseiwells.arucas.interpreter.Interpreter.execute(Interpreter.kt:659)
	at me.senseiwells.arucas.interpreter.Interpreter.interpret$Arucas(Interpreter.kt:244)
	at me.senseiwells.arucas.interpreter.ThreadHandler.execute$Arucas(ThreadHandler.kt:28)
	at me.senseiwells.arucas.interpreter.Interpreter$Mother.execute(Interpreter.kt:1310)
	at me.senseiwells.arucas.interpreter.Interpreter$executeAsync$1.invoke(Interpreter.kt:202)
	at me.senseiwells.arucas.interpreter.Interpreter$executeAsync$1.invoke(Interpreter.kt:202)
	at me.senseiwells.arucas.interpreter.ThreadHandler.async$lambda-0(ThreadHandler.kt:44)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.ByteBuddy
	... 31 more

```

**Comment by senseiwells** [comment]
Closing as won't fix, I plan on reworking the scripting system for the future.
