### ISSUE TITLE
Cannot open config screen

### ISSUE THREAD

**Issue by AStrongGuy** [senseiwells/EssentialClient#142]
mod version: EssentialClient 2.0.0-beta.1 for 1.21.1

Error from mod 'essential-client'
java.lang.NoSuchMethodError: 'me.senseiwells.chunkdebug.client.gui.ChunkDebugScreen me.senseiwells.chunkdebug.client.ChunkDebugClient.createChunkDebugScreen(net.minecraft.class_437)'
	at knot//me.senseiwells.essential_client.gui.EssentialClientScreen$Companion.createChunkDebugScreen(EssentialClientScreen.kt:70)
	at knot//me.senseiwells.essential_client.gui.EssentialClientScreen$Companion.createChunkDebugScreen$default(EssentialClientScreen.kt:69)
	at knot//me.senseiwells.essential_client.gui.EssentialClientScreen$Companion.canUseChunkDebug(EssentialClientScreen.kt:66)
	at knot//me.senseiwells.essential_client.gui.EssentialClientScreen$Companion.access$canUseChunkDebug(EssentialClientScreen.kt:62)
	at knot//me.senseiwells.essential_client.gui.EssentialClientScreen.method_25426(EssentialClientScreen.kt:37)
	at knot//net.minecraft.class_437.method_25423(class_437.java:309)
	at knot//net.minecraft.class_310.method_1507(class_310.java:1143)
	at knot//com.terraformersmc.modmenu.gui.ModsScreen.safelyOpenConfigScreen(ModsScreen.java:647)
	at knot//com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.openConfig(ModListEntry.java:182)
	at knot//com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25402(ModListEntry.java:172)
	at knot//com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25402(ModListWidget.java:294)
	at knot//net.minecraft.class_4069.method_25402(class_4069.java:38)
	at knot//net.minecraft.class_312.method_1611(class_312.java:107)
	at knot//net.minecraft.class_437.method_25412(class_437.java:431)
	at knot//net.minecraft.class_312.method_1601(class_312.java:107)
	at knot//net.minecraft.class_312.method_22686(class_312.java:196)
	at knot//net.minecraft.class_1255.execute(class_1255.java:108)
	at knot//net.minecraft.class_312.method_22684(class_312.java:196)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:303)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1307)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![2024-10-24_16 16 10](https://github.com/user-attachments/assets/12a22091-58e4-49d3-9f45-bc029a248a64)

**Comment by senseiwells** [comment]
Thank you, I have updated [ChunkDebug](https://modrinth.com/mod/chunk-debug/version/2.1.2+1.21.1), let me know if this fixes your issue

**Comment by AStrongGuy** [comment]
Thanks! This fixed the config menu not opening, but now I've encountered a new issue. When I try to open the Carpet Server Settings, my game crashes.

Here's the error message:

Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "carpet.api.settings.SettingsManager.getCarpetRules()" because "it" is null
	at knot//me.senseiwells.essential_client.utils.CarpetUtils.rules(CarpetUtils.kt:13)
	at knot//me.senseiwells.essential_client.features.carpet_client.SingleplayerCarpetClient.createCategories(SingleplayerCarpetClient.kt:46)
	at knot//me.senseiwells.essential_client.features.carpet_client.CarpetClient.createConfig(CarpetClient.kt:17)
	at knot//me.senseiwells.essential_client.gui.EssentialClientScreen.init$lambda$1(EssentialClientScreen.kt:32)
	at knot//net.minecraft.class_4185.method_25306(class_4185.java:96)
	at knot//net.minecraft.class_4264.method_25348(class_4264.java:48)
	at knot//net.minecraft.class_339.method_25402(class_339.java:141)
	at knot//net.minecraft.class_4069.method_25402(class_4069.java:38)
	at knot//net.minecraft.class_312.method_1611(class_312.java:107)
	at knot//net.minecraft.class_437.method_25412(class_437.java:431)
	at knot//net.minecraft.class_312.method_1601(class_312.java:107)
	at knot//net.minecraft.class_312.method_22686(class_312.java:196)
	at knot//net.minecraft.class_1255.execute(class_1255.java:108)
	at knot//net.minecraft.class_312.method_22684(class_312.java:196)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:303)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1307)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by senseiwells** [comment]
I have fixed this now in EssentialClient which you can download here: https://modrinth.com/mod/essentialclient/version/2.0.0-beta.2+1.21.1

Please let me know of any further issues

**Comment by AStrongGuy** [comment]
This doesn't seem to have fixed the issue.

This is the crash log when trying to open the menu while not in any server/world:
[crash-2024-10-24_17.13.46-client.txt](https://github.com/user-attachments/files/17512955/crash-2024-10-24_17.13.46-client.txt)

And this is the one I get while on my singleplayer world:
[crash-2024-10-24_17.18.31-client.txt](https://github.com/user-attachments/files/17512956/crash-2024-10-24_17.18.31-client.txt)

**Comment by senseiwells** [comment]
Try using this version of YACL: https://modrinth.com/mod/yacl/version/3.5.0+1.21-fabric

**Comment by AStrongGuy** [comment]
Thanks, I appreciate all your help. That fixed it.
