### ISSUE TITLE
Issue With VANILLA_BLOCK_EVENT_PACKET_RANGE String having a NumberFormatException? 1.16.5, I know you are not supporting it... version 1.1.6 of essential client

### ISSUE THREAD

**Issue by JacktheDevel0per** [senseiwells/EssentialClient#41]
https://pastebin.com/ydyMNQtr

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'essential-client'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NumberFormatException: For input string: "VANILLA_BLOCK_EVENT_PACKET_RANGE"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:556)
	at com.google.gson.JsonPrimitive.getAsDouble(JsonPrimitive.java:193)
	at essentialclient.feature.CarpetClient.jsonToClientRule(CarpetClient.java:175)
	at essentialclient.feature.CarpetClient.lambda$readConfig$10(CarpetClient.java:271)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at essentialclient.feature.CarpetClient.readConfig(CarpetClient.java:270)
	at essentialclient.feature.CarpetClient.readConfig(CarpetClient.java:23)
	at essentialclient.utils.config.Config.readConfig(Config.java:65)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at essentialclient.EssentialClient.onInitialize(EssentialClient.java:41)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 751536992 bytes (716 MB) / 1040187392 bytes (992 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by JacktheDevel0per** [comment]
is this a config issue?

**Comment by JacktheDevel0per** [comment]
Yep It Was Corrupt Config... Should Handle that and send it to signal but sorry.

**Comment by Crec0** [comment]
It was not corrupt config. It was as issue because of bug in carpet-rules-database. Fixed now and it should launch fine with no other actions required

**Comment by JacktheDevel0per** [comment]
Oh I see, I'm guessing if you started your game at the wrong time everyone would be effected?

**Comment by Crec0** [comment]
Essential client fetches the rules list from that repo on game startup. I pushed the fix 10 minutes ago. So anyone who launches now should be fine
