### ISSUE TITLE
Crash at startup - Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'essential-client'!

### ISSUE THREAD

**Issue by esskaypee** [senseiwells/EssentialClient#65]
PolyMC version: 1.4.1

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.165.195.37, 18.165.195.49, 18.165.195.40, 18.165.195.47]

session.minecraft.net resolves to:
    [52.45.69.223, 52.7.214.17, 3.229.83.86]

textures.minecraft.net resolves to:
    [18.165.201.65, 18.165.201.70, 18.165.201.77, 18.165.201.12]

api.mojang.com resolves to:
    [18.172.153.32, 18.172.153.35, 18.172.153.63, 18.172.153.104]

Minecraft folder is:
D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/instances/1.19/.minecraft

Java path is:
C:/Program Files/Amazon Corretto/jdk17.0.2_8/bin/javaw.exe

Checking Java version...
Java is version 17.0.2, using 64 (amd64) architecture, from Amazon.com Inc..

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/instances/1.19/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.1/lwjgl-glfw-natives-windows-x86-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.1/lwjgl-glfw-natives-windows-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.1/lwjgl-jemalloc-natives-windows-x86-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.1/lwjgl-jemalloc-natives-windows-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.1/lwjgl-natives-windows-x86-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-natives-windows/3.3.1/lwjgl-natives-windows-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.1/lwjgl-openal-natives-windows-x86-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.1/lwjgl-openal-natives-windows-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.1/lwjgl-opengl-natives-windows-x86-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.1/lwjgl-opengl-natives-windows-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.1/lwjgl-stb-natives-windows-x86-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.1/lwjgl-stb-natives-windows-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.1/lwjgl-tinyfd-natives-windows-x86-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.1/lwjgl-tinyfd-natives-windows-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/authlib/3.5.41/authlib-3.5.41.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/text2speech-natives-windows/1.13.9/text2speech-natives-windows-1.13.9.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/fabricmc/fabric-loader/0.14.8/fabric-loader-0.14.8.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/fabricmc/intermediary/1.19/intermediary-1.19.jar
  D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/com/mojang/minecraft/1.19/minecraft-1.19-client.jar

Native libraries:

Mods:
  [✔] advancementinfo-1.19-fabric0.53.3-1.3.1
  [✔] antighost-1.19-fabric0.55.3-1.1.5
  [✔] borderless-mining-1.1.5+1.19
  [✔] carpet-extra-1.19-1.4.79
  [✔] carpet-fixes-1.19-1.11.2
  [✔] carpet-tis-addition-mc1.19-v1.38.0
  [✔] chat-up-2.0.0
  [✔] clientcommands-2.7.1
  [✔] dark-loading-screen-1.6.12
  [✔] essential-client-1.19-1.2.3
  [✔] essentialaddons-1.19-1.1.4
  [✔] fabric-api-0.58.0+1.19
  [✔] fabric-carpet-1.19-1.4.79+v220607
  [✔] fabric-language-kotlin-1.8.2+kotlin.1.7.10
  [✔] indium-1.0.6+mc1.19
  [✔] iris-mc1.19.1-1.2.6
  [✔] itemscroller-fabric-1.19-craftfix-1.2.6
  [✔] lambdabettergrass-1.3.0+1.19
  [✔] lambdynamiclights-2.1.2+1.19
  [✔] litematica-fabric-1.19-0.11.3
  [✔] lithium-fabric-mc1.19-0.8.1
  [✔] magiclib-0.5.32
  [✔] malilib-fabric-1.19-0.12.1
  [✔] MasaGadget-3.0.0
  [✔] minihud-fabric-1.19-0.22.0
  [✔] modmenu-4.0.4
  [✔] multiconnect-1.6-beta.20
  [✔] notenoughcrashes-4.1.6+1.19-fabric
  [✔] reeses_sodium_options-1.4.4+mc1.19-build.47
  [✘] replaymod-1.19-2.6.6.jar (disabled)
  [✔] sodium-extra-0.4.6+mc1.19-build.47
  [✔] sodium-fabric-mc1.19-0.4.2 (replaymod compatible)
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] thorium-1.3.1
  [✔] tooltipfix-1.0.5-1.19
  [✔] tweakermore-mc1.19-v3.6.1
  [✔] tweakfork-fabric-1.19-1.2.3
  [✔] viafabric-0.4.7+11-main
  [✔] worldedit-mod-7.2.11-beta-02-dist
  [✔] WorldEditCUI-1.19+01
  [✔] Xaeros_Minimap_22.12.0_Fabric_1.19
  [✔] XaerosWorldMap_1.26.1_Fabric_1.19

Params:
  --username  --version 1.19 --gameDir D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/instances/1.19/.minecraft --assetsDir D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 1920 x 1080

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 11936

[22:19:43] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[22:19:43] [ForkJoinPool-1-worker-3/WARN]: Mod itemscroller uses the version craftfix-1.2.6 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'craftfix'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:19:44] [main/INFO]: Loading 122 mods:
	- advancementinfo 1.19-fabric0.53.3-1.3.1
	- antighost 1.19-fabric0.55.3-1.1.5
	- borderlessmining 1.1.5+1.19
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- carpet 1.4.79
	- carpet-extra 1.4.79
	- carpet-fixes 1.19-1.11.2
	- carpet-tis-addition 1.38.0
	- chat-up 2.0
	- clientarguments 1.4.1 via clientcommands
	- clientcommands 2.7.1
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.42 via advancementinfo
	- com_github_llamalad7_mixinextras 0.0.6 via carpet-fixes
	- com_typesafe_config 1.4.2 via thorium
	- conditional-mixin 0.3.1 via carpet-tis-addition
	- crowdin-translate 1.4+1.19 via antighost
	- dark-loading-screen 1.6.12
	- essential-client 1.19-1.2.3
	- essentialaddons 1.19-1.1.4
	- fabric 0.58.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.28+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.1+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.2+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.5+35a03c43a9 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.1+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.1.0+442de8b8a9 via fabric
	- fabric-networking-v0 0.3.15+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.18+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.10+5187d39fa9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e0a9 via fabric
	- fabric-screen-api-v1 1.0.24+f05effafa9 via fabric
	- fabric-screen-handler-api-v1 1.2.7+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.8
	- indium 1.0.6+mc1.19
	- io_leangen_geantyref_geantyref 1.3.13 via thorium
	- iris 1.2.6
	- itemscroller craftfix-1.2.6
	- java 17
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.1.2+1.19
	- litematica 0.11.3
	- lithium 0.8.1
	- magiclib 0.5.32
	- magiclib-1_19 0.5.32 via magiclib
	- malilib 0.12.1
	- masa_gadget_mod 3.0.0
	- masa_gadget_mod-1_19 3.0.0 via masa_gadget_mod
	- minecraft 1.19
	- minihud 0.22.0
	- modmenu 4.0.4
	- multiconnect 1.6-beta.20
	- multiconnect-api 1.6-beta.20 via multiconnect
	- notenoughcrashes 4.1.6+1.19
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via thorium
	- org_spongepowered_configurate-hocon 4.1.2 via thorium
	- org_yaml_snakeyaml 1.30 via carpet-tis-addition
	- pride 1.1.2+1.19 via lambdynlights
	- reeses-sodium-options 1.4.4+mc1.19-build.47
	- sodium 0.4.2+replaymod.rev.bfbc6de
	- sodium-extra 0.4.6+mc1.19-build.47
	- spruceui 4.0.0+1.19 via lambdabettergrass
	- starlight 1.1.1+fabric.ae22326
	- thorium 1.3.1
	- tooltipfix 1.0.5-1.19
	- tweakermore 3.6.1
	- tweakeroo 1.2.3
	- viafabric 0.4.7+11-main
	- viafabric-mc119 0.4.7+11-main via viafabric
	- viaversion 4.4.0-1.19.1-rc2-SNAPSHOT via viafabric
	- worldedit 7.2.11-beta-02+315c5d0
	- worldeditcui 1.19+01
	- xaerominimap 22.12.0
	- xaeroworldmap 1.26.1
[22:19:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Minecraft/Tools/PolyMC-Windows-Portable-1.4.1/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:19:44] [main/INFO]: Compatibility level set to JAVA_17
[22:19:45] [main/WARN]: Reference map 'clientarguments-refmap.json' for clientarguments.mixins.json could not be read. If this is a development environment you can ignore this message
[22:19:45] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 1 override(s) found
[22:19:46] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[22:19:46] [main/INFO]: Loaded configuration file for Sodium Extra: 27 options available, 0 override(s) found
[22:19:47] [main/WARN]: Force-disabling mixin 'entity.data_tracker.no_locks.DataTrackerMixin' as rule 'mixin.entity.data_tracker' (added by mods [multiconnect]) disables it and children
[22:19:47] [main/WARN]: Force-disabling mixin 'entity.data_tracker.use_arrays.DataTrackerMixin' as rule 'mixin.entity.data_tracker' (added by mods [multiconnect]) disables it and children
[22:19:47] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[22:19:48] [main/WARN]: [carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinLevelChunkSetBlockHook
[22:19:48] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'essential-client'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'essential-client'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.8.jar:?]
	... 11 more
Caused by: java.lang.LinkageError: loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4883b407 attempted duplicate class definition for com.llamalad7.mixinextras.MixinExtrasBootstrap. (com.llamalad7.mixinextras.MixinExtrasBootstrap is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4883b407, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @5622fdf)
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.8.jar:?]
	... 11 more
Process exited with code 1.
Clipboard copy at: 01 Aug 2022 22:25:22 +0100

**Comment by senseiwells** [comment]
This has been fixed
