### ISSUE TITLE
Please update to 1.19.2 ❤️

### ISSUE THREAD

**Issue by mrniddala** [senseiwells/EssentialClient#68]
Mixin apply for mod essential-client failed essentialclient.mixins.json:core.ClientPlayerEntityMixin from mod essential-client -> net.minecraft.class_746: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_44099 in essentialclient.mixins.json:core.ClientPlayerEntityMixin from mod essential-client was not located in the target class net.minecraft.class_746. Using refmap essential-client-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_44099 in essentialclient.mixins.json:core.ClientPlayerEntityMixin from mod essential-client was not located in the target class net.minecraft.class_746. Using refmap essential-client-refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.item.ItemGroup.<init>(ItemGroup:114)
	at net.minecraft.class_1761$1.<init>(class_1761.java:15)
	at net.minecraft.item.ItemGroup.<clinit>(ItemGroup:15)
	at net.minecraft.item.Items.<clinit>(Items:22)
	at net.minecraft.item.Item.fromBlock(Item:74)
	at net.minecraft.block.Block.asItem(Block:554)
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.createAndRegister(FlatLevelGeneratorPresets:60)
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.initAndGetDefault(FlatLevelGeneratorPresets:66)
	at net.minecraft.world.gen.FlatLevelGeneratorPresets.initAndGetDefault(FlatLevelGeneratorPresets:199)
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98)
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104)
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326)
	at net.minecraft.Bootstrap.initialize(Bootstrap:50)
	at net.minecraft.client.main.Main.method_44604(Main:161)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
15:24:56.984
FabricLoader
main
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.item.Items.<clinit>(Items:22)
	at net.minecraft.item.Item.fromBlock(Item:74)
	at net.minecraft.block.Block.asItem(Block:554)
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.createAndRegister(FlatLevelGeneratorPresets:60)
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.initAndGetDefault(FlatLevelGeneratorPresets:66)
	at net.minecraft.world.gen.FlatLevelGeneratorPresets.initAndGetDefault(FlatLevelGeneratorPresets:199)
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98)
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104)
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326)
	at net.minecraft.Bootstrap.initialize(Bootstrap:50)
	at net.minecraft.client.main.Main.method_44604(Main:161)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.item.ItemGroup.<init>(ItemGroup:114)
	at net.minecraft.class_1761$1.<init>(class_1761.java:15)
	at net.minecraft.item.ItemGroup.<clinit>(ItemGroup:15)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 24 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [essentialclient.mixins.json:core.ClientPlayerEntityMixin from mod essential-client] from phase [DEFAULT] in config [essentialclient.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 27 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_44099 in essentialclient.mixins.json:core.ClientPlayerEntityMixin from mod essential-client was not located in the target class net.minecraft.class_746. Using refmap essential-client-refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 27 more

**Comment by Earthcomputer** [comment]
https://cdn.discordapp.com/attachments/918649771844042752/1002310019976532098/essential-client-1.19.1-1.2.4-BETA-280722.jar

**Comment by mrniddala** [comment]
Thank you so much 😋

**Comment by senseiwells** [comment]
Thanks Earth, I will just upload a pre-release until I'm finished with the update.
